'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.18444
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Функциональные возможности автосохранения My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Manual")>  _
        Public Property NeDataSqlConnectionMode() As String
            Get
                Return CType(Me("NeDataSqlConnectionMode"),String)
            End Get
            Set
                Me("NeDataSqlConnectionMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Text")>  _
        Public Property NeDataSqlCommandType() As String
            Get
                Return CType(Me("NeDataSqlCommandType"),String)
            End Get
            Set
                Me("NeDataSqlCommandType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Custom")>  _
        Public Property NeDataSqlCacheType() As String
            Get
                Return CType(Me("NeDataSqlCacheType"),String)
            End Get
            Set
                Me("NeDataSqlCacheType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property NeDataSqlCacheDuration() As String
            Get
                Return CType(Me("NeDataSqlCacheDuration"),String)
            End Get
            Set
                Me("NeDataSqlCacheDuration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\cache\unitTest")>  _
        Public Property NeDataSqlCachePath() As String
            Get
                Return CType(Me("NeDataSqlCachePath"),String)
            End Get
            Set
                Me("NeDataSqlCachePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("104857600")>  _
        Public Property NeDataSqlCacheBufferSize() As String
            Get
                Return CType(Me("NeDataSqlCacheBufferSize"),String)
            End Get
            Set
                Me("NeDataSqlCacheBufferSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UnitTestHelper.MyCache")>  _
        Public Property NeDataSqlCacheCustom() As String
            Get
                Return CType(Me("NeDataSqlCacheCustom"),String)
            End Get
            Set
                Me("NeDataSqlCacheCustom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(" 1, test, 01.01.2014")>  _
        Public Property NeDataSqlCacheCustomArgs() As String
            Get
                Return CType(Me("NeDataSqlCacheCustomArgs"),String)
            End Get
            Set
                Me("NeDataSqlCacheCustomArgs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00:00:00.500")>  _
        Public Property NeDataSqlCacheBufferAccessTimeout() As String
            Get
                Return CType(Me("NeDataSqlCacheBufferAccessTimeout"),String)
            End Get
            Set
                Me("NeDataSqlCacheBufferAccessTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00:00:00.300")>  _
        Public Property NeDataSqlCacheAccessTimeout() As String
            Get
                Return CType(Me("NeDataSqlCacheAccessTimeout"),String)
            End Get
            Set
                Me("NeDataSqlCacheAccessTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UnitTestHelper.MyCacheBinder")>  _
        Public Property NeDataSqlCacheBinder() As String
            Get
                Return CType(Me("NeDataSqlCacheBinder"),String)
            End Get
            Set
                Me("NeDataSqlCacheBinder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\example.mdf;Integrated "& _ 
            "Security=True;User Instance=True")>  _
        Public Property LocalSqlServer() As String
            Get
                Return CType(Me("LocalSqlServer"),String)
            End Get
            Set
                Me("LocalSqlServer") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.VBSqlClientConfigTest.My.MySettings
            Get
                Return Global.VBSqlClientConfigTest.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
