CREATE TABLE [dbo].[types]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [type_bigint] BIGINT NULL, 
    [type_binary_50] BINARY(50) NULL, 
    [type_bit] BIT NULL, 
    [type_char_10] CHAR(10) NULL, 
    [type_date] DATE NULL, 
    [type_datetime] DATETIME NULL, 
    [type_datetime2] DATETIME2 NULL, 
    [type_datetimeoffset] DATETIMEOFFSET NULL, 
    [type_decimal] DECIMAL NULL, 
    [type_float] FLOAT NULL, 
    [type_image] IMAGE NULL, 
    [type_int] INT NULL, 
    [type_money] MONEY NULL, 
    [type_nchar] NCHAR(10) NULL, 
    [type_ntext] NTEXT NULL, 
    [type_numeric] NUMERIC NULL, 
    [type_nvarchar_50] NVARCHAR(50) NULL, 
    [type_nvarchar_max] NVARCHAR(MAX) NULL, 
    [type_real] REAL NULL, 
    [type_rowversion] ROWVERSION NULL, 
    [type_smalldatetime] SMALLDATETIME NULL, 
    [type_smallint] SMALLINT NULL, 
    [type_smallmoney] SMALLMONEY NULL, 
    [type_sql_variant] SQL_VARIANT NULL, 
    [type_text] TEXT NULL, 
    [type_time] TIME NULL, 
    [type_tinyint] TINYINT NULL, 
    [type_uniqueidentifier] UNIQUEIDENTIFIER NULL, 
    [type_xml] XML NULL
)
