//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpSqlClientConfigTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manual")]
        public string NeDataSqlConnectionMode {
            get {
                return ((string)(this["NeDataSqlConnectionMode"]));
            }
            set {
                this["NeDataSqlConnectionMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Text")]
        public string NeDataSqlCommandType {
            get {
                return ((string)(this["NeDataSqlCommandType"]));
            }
            set {
                this["NeDataSqlCommandType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom")]
        public string NeDataSqlCacheType {
            get {
                return ((string)(this["NeDataSqlCacheType"]));
            }
            set {
                this["NeDataSqlCacheType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int NeDataSqlCacheDuration {
            get {
                return ((int)(this["NeDataSqlCacheDuration"]));
            }
            set {
                this["NeDataSqlCacheDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\cache\\unitTest")]
        public string NeDataSqlCachePath {
            get {
                return ((string)(this["NeDataSqlCachePath"]));
            }
            set {
                this["NeDataSqlCachePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104857600")]
        public long NeDataSqlCacheBufferSize {
            get {
                return ((long)(this["NeDataSqlCacheBufferSize"]));
            }
            set {
                this["NeDataSqlCacheBufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UnitTestHelper.MyCache")]
        public string NeDataSqlCacheCustom {
            get {
                return ((string)(this["NeDataSqlCacheCustom"]));
            }
            set {
                this["NeDataSqlCacheCustom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" 1, test, 01.01.2014")]
        public string NeDataSqlCacheCustomArgs {
            get {
                return ((string)(this["NeDataSqlCacheCustomArgs"]));
            }
            set {
                this["NeDataSqlCacheCustomArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00:00:00.500")]
        public string NeDataSqlCacheBufferAccessTimeout {
            get {
                return ((string)(this["NeDataSqlCacheBufferAccessTimeout"]));
            }
            set {
                this["NeDataSqlCacheBufferAccessTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00:00:00.300")]
        public string NeDataSqlCacheAccessTimeout {
            get {
                return ((string)(this["NeDataSqlCacheAccessTimeout"]));
            }
            set {
                this["NeDataSqlCacheAccessTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UnitTestHelper.MyCacheBinder")]
        public string NeDataSqlCacheBinder {
            get {
                return ((string)(this["NeDataSqlCacheBinder"]));
            }
            set {
                this["NeDataSqlCacheBinder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\example.mdf;Integrated " +
            "Security=True;User Instance=True")]
        public string LocalSqlServer {
            get {
                return ((string)(this["LocalSqlServer"]));
            }
            set {
                this["LocalSqlServer"] = value;
            }
        }
    }
}
